spring.application.name=PBL-Spring
server.port=8080

# Swagger UI 설정
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true

# 프로젝트 정보
springdoc.info.title=Member API
springdoc.info.description=멤버 관리 REST API
springdoc.info.version=1.0.0


